[package]
name = "CipherQuest"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "a41ee41c3ce6" }

[addresses]
cipher_addr = "0x3a3ee68a300bcdf150ac3386e4ddc379a55dfafd84a09f1a0ec57111a4381cc6"
